package com.walkmission.domain.user.entity;

import com.walkmission.global.entity.BaseTimeEntity;
import jakarta.persistence.*;
import java.time.LocalDate;
import java.util.UUID;

@Entity
@Table(name = "users")
public class User extends BaseTimeEntity {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private UUID userUuid;

    @Column(unique = true, nullable = false)
    private String email;

    private String password;
    private String nickname;
    private String profileImageUrl;
    private LocalDate birth;
    private String regionCode;

    // Getters and protected no-arg constructor are typically generated by Lombok, 
    // but we write basic ones if Lombok is not used. Since Lombok isn't added, we can just leave it as standard POJO fields.
    protected User() {}
}
